"""`start_workflow` / `workflow_control` — the tools that let the model drive
the Big Five workflow (PRD §9.3).

Both return `ToolResult.direct_sentences`: the workflow's own reply is spoken
verbatim (guarded, but never re-generated by a second LLM hop) — see
`RunTurn`'s tool-hop loop.
"""

from __future__ import annotations

from typing import Any, ClassVar, Literal, cast

from sarjy.contexts.assessment.application.control_run import ControlRun
from sarjy.contexts.assessment.application.start_run import StartRun
from sarjy.contexts.conversation.application.ports import Fact, ToolResult
from sarjy.shared.ids import UserId

KNOWN_WORKFLOWS = ("ocean_mini_ipip",)
_ACTIONS = ("resume", "quit")


class StartWorkflowTool:
    # Not `ClassVar` (unlike `declaration` below): `ToolPort.name` is a plain
    # `str`, and a Protocol member declared as an instance variable rejects a
    # `ClassVar` implementation even though the value itself never varies per
    # instance — see `GetWeatherTool`/the memory tools for the same pattern.
    name = "start_workflow"
    mutating: ClassVar[bool] = True  # opens a run (L-3)
    declaration: ClassVar[dict[str, Any]] = {
        "name": "start_workflow",
        "description": (
            "Begin a multistep flow. Currently only 'ocean_mini_ipip' (Big Five "
            "personality test). Call when the user asks for a personality test."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "workflow_id": {"type": "string", "enum": ["ocean_mini_ipip"]},
            },
            "required": ["workflow_id"],
        },
    }

    def __init__(self, start_run: StartRun) -> None:
        self.start_run = start_run

    async def invoke(
        self, user_id: UserId, args: dict[str, Any], facts: list[Fact] | None = None
    ) -> ToolResult:
        wid = str(args.get("workflow_id", ""))
        if wid not in KNOWN_WORKFLOWS:
            return ToolResult(
                ok=False,
                data={"error": "unknown_workflow"},
                spoken_error="I only have the Big Five personality test right now.",
            )
        reply = await self.start_run.execute(user_id, wid)
        return ToolResult(
            ok=True,
            data={"sentences": reply.sentences, "workflow": reply.workflow},
            grounding_numbers=reply.grounding_numbers,
            direct_sentences=list(reply.sentences),
        )


class WorkflowControlTool:
    name = "workflow_control"  # see `StartWorkflowTool.name` for why not ClassVar
    mutating: ClassVar[bool] = True  # resumes or quits a run (L-3)
    declaration: ClassVar[dict[str, Any]] = {
        "name": "workflow_control",
        "description": "Control an active workflow: continue after a pause, or quit.",
        "parameters": {
            "type": "object",
            "properties": {"action": {"type": "string", "enum": ["resume", "quit"]}},
            "required": ["action"],
        },
    }

    def __init__(self, control_run: ControlRun) -> None:
        self.control_run = control_run

    async def invoke(
        self, user_id: UserId, args: dict[str, Any], facts: list[Fact] | None = None
    ) -> ToolResult:
        action = args.get("action")
        if action not in _ACTIONS:
            return ToolResult(
                ok=False,
                data={"error": "bad_action"},
                spoken_error="I can continue or quit the test — which one?",
            )
        # `action in _ACTIONS` already proved this above; the cast just spells
        # it out for mypy, which cannot narrow a plain `str` to the `Literal`
        # `ControlRun.execute` expects from an `in` check alone.
        reply = await self.control_run.execute(user_id, cast(Literal["resume", "quit"], action))
        return ToolResult(
            ok=True,
            data={"sentences": reply.sentences, "workflow": reply.workflow},
            grounding_numbers=reply.grounding_numbers,
            direct_sentences=list(reply.sentences),
        )
